#ifndef MAKAILIB_GRAPH_H
#define MAKAILIB_GRAPH_H

#define MKGRAPH_OPENGL (1)

#ifndef MKGRAPH_GRAPHICAL_API
#define MKGRAPH_GRAPHICAL_API MKGRAPH_OPENGL
#endif

#if MKGRAPH_GRAPHICAL_API == MKGRAPH_OPENGL
#include "gl/graph.hpp"
#endif

#endif // MAKAILIB_GRAPH_H
