#ifndef MAKAI_GAME_SYSTEM_LAYOUT
#define MAKAI_GAME_SYSTEM_LAYOUT

#ifndef SUBLAYER_COUNT
#define SUBLAYER_COUNT 8
#endif // SUBLAYER_COUNT

#ifndef UI_LAYER_OFFSET
#define UI_LAYER_OFFSET 32
#endif // UI_LAYER_OFFSET

#define R_LAYER(NAME) \
	NAME##_$_$, \
    NAME##_LAYER = (NAME##_$_$ + (SUBLAYER_COUNT - 1))

#define CR_LAYER(NAME, INDEX) NAME##_LAYER = ((INDEX) + (SUBLAYER_COUNT - 1))

#define $sublayer(INDEX) ((INDEX) - (SUBLAYER_COUNT - 1))

namespace Layer {
	enum Layer: size_t {
		R_LAYER(WORLD),
		#ifdef $_DANMAKU_GAME
		R_LAYER(SPELL),
		R_LAYER(PLAYER),
		R_LAYER(PLAYER_BULLET),
		R_LAYER(PLAYER_LASER),
		R_LAYER(PLAYER_BOMB),
		R_LAYER(ENEMY),
		R_LAYER(ENEMY_BULLET),
		R_LAYER(ENEMY_LASER),
		R_LAYER(ITEM),
		R_LAYER(PLAYER_HITBOX),
		#endif
		CR_LAYER(UI, UI_LAYER_OFFSET * SUBLAYER_COUNT),
		CR_LAYER(DIALOG, UI_LAYER)
	};
}

#undef R_LAYER
#undef CR_LAYER

#define $layer(NAME) Layer::NAME##_LAYER

#endif // MAKAI_GAME_SYSTEM_LAYOUT
