#ifndef MAX_INSTANCE_COUNT
#define MAX_INSTANCE_COUNT 4096
#endif // MAX_INSTANCE_COUNT

#ifndef PLAYER_LASER_COUNT
#define PLAYER_LASER_COUNT 32
#endif // PLAYER_LASER_COUNT

#ifndef PLAYER_BULLET_COUNT
#define PLAYER_BULLET_COUNT 64
#endif // PLAYER_BULLET_COUNT

#ifndef ENEMY_LASER_COUNT
#define ENEMY_LASER_COUNT 128
#endif // ENEMY_LASER_COUNT

#ifndef ENEMY_BULLET_COUNT
#define ENEMY_BULLET_COUNT MAX_INSTANCE_COUNT - (PLAYER_BULLET_COUNT + PLAYER_LASER_COUNT + ENEMY_LASER_COUNT)
#endif // ENEMY_BULLET_COUNT

#define $getman(TYPE) $dmk TYPE##Manager
#define $setman(TYPE) $dmk TYPE##Manager = &

namespace ItemType {
	enum ItemType: size_t {
		POWER_ITEM,
		POINT_ITEM,
		EXTRA_ITEM,
		BOMB_ITEM,
		LIFE_ITEM
	};
};

#define $item(NAME) ItemType::NAME##_ITEM
