#ifndef CTL_NAMESPACE_H
#define CTL_NAMESPACE_H

#define CTL_NAMESPACE_BEGIN	namespace CTL {
#define CTL_NAMESPACE_END	}

CTL_NAMESPACE_BEGIN

namespace CTL = ::CTL;

CTL_NAMESPACE_END

#endif // CTL_NAMESPACE_H
