#ifndef CTL_INCLUDE_ALL_H
#define CTL_INCLUDE_ALL_H

#include "legacy/helper.hpp"
#include "legacy/ctl/ctypes.hpp"
#include "legacy/ctl/typeinfo.hpp"
#include "legacy/conceptual.hpp"
#include "legacy/referential.hpp"
#include "legacy/algebra.hpp"
#include "legacy/definitions.hpp"
#include "legacy/dataview.hpp"
#include "legacy/threaddata.hpp"
#include "legacy/asynchronous.hpp"
#include "legacy/errors.hpp"
#include "legacy/vectorn.hpp"
#include "legacy/matrices.hpp"
#include "legacy/cyclical.hpp"
#include "legacy/tween.hpp"
#include "legacy/event.hpp"
#include "legacy/tasking.hpp"
#include "legacy/grouping.hpp"
#include "legacy/sharedvalue.hpp"
#include "legacy/splines.hpp"
#include "legacy/waves.hpp"
#include "legacy/variant.hpp"
#include "legacy/collisions.hpp"
#include "legacy/entity/entity.hpp"
#include "legacy/obfuscator.hpp"
//#include "legacy/filehandler.hpp"

#endif // CTL_INCLUDE_ALL_H
