#ifndef MAKAILIB_GRAPH_SHADERCODE_DECLARE_CC
#define MAKAILIB_GRAPH_SHADERCODE_DECLARE_CC

#define SHADER_BEGIN(NAME)	String const NAME =
#define SHADER_END			;

#endif // MAKAILIB_GRAPH_SHADERCODE_DECLARE_CC
