name: Core Library CI

on:
  schedule:
    - cron: '30 9 * * 1'
#  push:
#    branches: [ "!legacy-system" ]
  workflow_dispatch:
  workflow_call:
#  pull_request:
#    types: [ "closed" ]
#    branches: [ "!legacy-system" ]

jobs: 

  install-gcc:
    name: Install Latest GCC
    runs-on: windows-2022
    steps:
    - name: Setup Compiler
      id: gccx
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: gcc-latest

    - name: Verify GCC Installation
      run: |
        gcc --version
        g++ --version
#      env:
#        CC: ${{ steps.gccx.outputs.cc }}
#        CXX: ${{ steps.gccx.outputs.cxx }}

  build-ctl-tests-debug:
    name: Build CTL Tests (DEBUG)
    runs-on: windows-2022
    needs: install-gcc
    steps:
      - uses: actions/checkout@v4
      - name: make tests
        run: |
          cd tests/ctl
          make debug
          cd ../..
#        env:
#          CC: ${{ steps.gccx.outputs.cc }}
#          CXX: ${{ steps.gccx.outputs.cxx }}
      - uses: actions/upload-artifact@master
        with:
          name: tests-ctl-debug
          path: tests/ctl/output/debug

  build-ctl-tests-release:
    name: Build CTL Tests (RELEASE)
    runs-on: windows-2022
    needs: install-gcc
    steps:
      - uses: actions/checkout@v4
      - name: make tests
        run: |
          cd tests/ctl
          make release
          cd ../..
#        env:
#          CC: ${{ steps.gccx.outputs.cc }}
#          CXX: ${{ steps.gccx.outputs.cxx }}
      - uses: actions/upload-artifact@master
        with:
          name: tests-ctl-release
          path: tests/ctl/output/release

  build-core-lib-debug:
    name: Build Makai (DEBUG)
    runs-on: windows-2022
    needs: install-gcc
    steps:
    - uses: actions/checkout@v4
    - name: make debug
      run: make debug
#      env:
#        CC: ${{ steps.gccx.outputs.cc }}
#        CXX: ${{ steps.gccx.outputs.cxx }}
    - uses: actions/upload-artifact@master
      with:
        name: lib-debug
        path: output

  build-core-lib-release:
    name: Build Makai (RELEASE)
    runs-on: windows-2022
    needs: install-gcc
    steps:
    - uses: actions/checkout@v4
    - name: make release
      run: make release
#      env:
#        CC: ${{ steps.gccx.outputs.cc }}
#        CXX: ${{ steps.gccx.outputs.cxx }}
    - uses: actions/upload-artifact@master
      with:
        name: lib-release
        path: output
        
  build-lib-tests-debug:
    name: Build API Tests (DEBUG)
    runs-on: windows-2022
    needs: [build-core-lib-debug]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@master
        with:
          name: lib-debug
          path: output
      - name: make tests
        run: |
          cd tests/makai
          make debug
          cd ../..
      - uses: actions/upload-artifact@master
        with:
          name: tests-api-debug
          path: tests/makai/output/debug

  build-lib-tests-release:
    name: Build API Tests (RELEASE)
    runs-on: windows-2022
    needs: [build-core-lib-release]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@master
        with:
          name: lib-release
          path: output
      - name: make tests
        run: |
          cd tests/makai
          make release
          cd ../..
      - uses: actions/upload-artifact@master
        with:
          name: tests-api-release
          path: tests/makai/output/release
